steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=$_IMAGE_NAME:$COMMIT_SHA
      - --tag=$_IMAGE_NAME:latest
      - --cache-from=$_IMAGE_NAME:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: Docker Push
    args:
      - push
      - --all-tags
      - $_IMAGE_NAME

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Get Credentials
    entrypoint: gcloud
    args:
      - container
      - clusters
      - get-credentials
      - $_CLUSTER_NAME
      - --zone=$_CLUSTER_ZONE
      - --project=$PROJECT_ID
    waitFor: ['Docker Push']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Rollout Restart
    entrypoint: kubectl
    args:
      - rollout
      - restart
      - deployment/sortshow
    waitFor: ['Get Credentials']

images:
  - $_IMAGE_NAME:$COMMIT_SHA
  - $_IMAGE_NAME:latest

options:
  logging: CLOUD_LOGGING_ONLY
