server {
    listen 8080;
    listen [::]:8080;
    server_name localhost;

    location /sortshow/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /sortshow/index.html;
    }
}
